version: '3.8'
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: sh -c "yarn install --frozen-lockfile && yarn start:dev"
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/app
      - /app/node_modules